name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: deploy simulation staging
        run: |
          echo 'deployed successfully to staging'
  deployment-prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy simulation production
        run: |
          echo 'deployed successfully to production'
